### ISSUE TITLE
Change to cloud run instead of cloud functions

### ISSUE THREAD

**Issue by thibaultmol** [LuisMayo/media-srt-generator#5] opened 2019-12-10 11:21 UTC
Hey,

The 9 minute runtime issue with cloud functions could actually be avoided by using Cloud run instead  (also serverless).

https://medium.com/google-cloud/cloud-run-vs-cloud-functions-whats-the-lowest-cost-728d59345a2e

https://medium.com/google-cloud/cloud-run-and-cloud-function-what-i-use-and-why-12bb5d3798e1

And would also allow you to put a 'cloud run' button on your project so it's easier to click and run your project for other people https://github.com/GoogleCloudPlatform/cloud-run-button

**Comment by LuisMayo** [comment] 2019-12-10 11:37
Hi!
I appreciate the idea and I'll look into it as the 9-minute limit is what I dislike the most about my current setup, because, Ideally, I'd want the project to work without having to visit the GC-Console in any moment after initial setup

I'll get information about it.
Thanks!

**Comment by LuisMayo** [comment] 2019-12-10 18:09
This is now fixed, button is also added.
I've updated https://gist.github.com/LuisMayo/8e7b95dee866841b218e046ddebb4028 with information
Thanks for the advice!

**Comment by thibaultmol** [comment] 2019-12-11 07:32
That was quick! I tried it out but it seems like I get an error (after I changed the environment variable and started it up again).
This is what stackdriver says about the logs: 
https://drive.google.com/open?id=1U8RTiiNK6i5UVLU48pszCZ4hEZQXixMb

btw, you can actually allow the user to set the environmental from the cloud shell when creating the cloud run instance in the first place: https://github.com/GoogleCloudPlatform/cloud-run-button#customizing-deployment-parameters

Also, did it automatically give you the right permissions for the storage bucket? Because it seems like that's something that doesn't automatically happen yet? https://github.com/GoogleCloudPlatform/cloud-run-button/issues/66
(also, you don't need storage buckets in theory, cause even .wav files aren't that massive and can just be stored in the cloud run's own storage (ram it seems) https://stackoverflow.com/questions/55908257/whats-the-default-storage-for-google-cloud-run

**Comment by LuisMayo** [comment] 2019-12-11 10:07
Hi again
Looking at the stack trace it seems that you have tried to open the URL using the navigator, instead put that URL into my frontend to craft the petition
https://luismayo.github.io/media-srt-generator-front/
Maybe I should set a redirect up so if you do a get request you get redirected to the frontend application

I'll check about environmental variables later, thanks for the tip!

I don't think it gives you permissions, you should set them manually.

Audio -> FLAC conversion is done in ram/in temp filesystem and I'm cool with that. The problem is that Google's speech to text audio can only gather the audio file from a Google Cloud Storage Bucket so that's basically the reason I need a bucket set up

Thanks!

**Closed as completed** 2019-12-11 13:08 UTC
Labels: enhancement, good first issue

**Comment by LuisMayo** [comment] 2019-12-11 19:25
Just so you know @thibaultmol I have pushed another version of the backend so now if you do navigate to the URL provided by Google Cloud Run It'll work!
Regards!

**Comment by thibaultmol** [comment] 2019-12-11 20:48
You don't actually need it to put it on a storage bucket, see the example on this page: https://cloud.google.com/speech-to-text/docs/quickstart-client-libraries

Also, (and this is just my opinion, so feel free to do with that what you prefer). But if I deploy this project, I expect everything to work out of the box. So when I click on that link on the cloud run project page, I expect to see the actual interface as well. (so not having to go to that seperate page and put in those details. Everything should happen on one page).

**Comment by thibaultmol** [comment] 2019-12-11 21:12
EDIT: I do see that the change you made does make it automatically open the github.io page. But I guess what i'm trying to say is that I'd be nice if that wasn't needed and everything was self contained in the cloud run instance without needing any 3rd party pages. (but that means it's probably best if that instance has some kind of 'google login' style authentication: https://cloud.google.com/appengine/docs/standard/python/oauth/ )

**Comment by LuisMayo** [comment] 2019-12-11 21:20
You do need to use a bucket
Base64 serialization is only available for audios under 1 minute

>  Audio longer than ~1 minute must use the uri field to reference an audio file in Google Cloud Storage.

[source: Quotas page on documentation](https://cloud.google.com/speech-to-text/quotas)

Regarding your second concern, everything working out of the box will be desirable but hard to actually execute, current problems include not being able to set the permissions through the button, not being able to create the bucket through the button and not being able to change timeout through the button (see https://github.com/GoogleCloudPlatform/cloud-run-button/issues/108 )

Anyway using the latest version (you can use again the button to update your copy) will redirect you to the frontend application on click so I think it would be pretty much out of the box

In the interface you only need to set the URL of the media you want to rip Subtitles from and a filename(backend URL would be already filled). I think filling this two fields is pretty understandable and logical for the end user so I don't think there is a lot more optimisation in this direction (although name could be avoidable and use the name from the media URL directly)

So right now (and thanks to you) the app is pretty much straightforward

However I'd appreciate any other optimisation you may have in mind and I'd consider them

Regards and thanks

**Comment by LuisMayo** [comment] 2019-12-11 21:35
@thibaultmol Regarding your edit
I see what you're trying to say. But I like to keep front and back isolated

The project could be the same basically serving the page from within the same URL, (I think that's what you're trying to say?), however I see little to no gain from this.

By isolating front and back I'm able to deploy and add functionality in front without going to the hassle of publishing a new docker container and waiting the 10 minutes from testing, plus you could adapt the backend to your necesites but still use the same front

In general guidelines I like isolation

If you want to by some way embed a client into the backend you're free to go, I may review a Pull request in this direction and approve it but I'm not doing it myself since I think the current arch doesn't really give any problems that wouldn't exist otherwise

I hope I'm not giving a rude impression, I really appreciate your suggestions and I encourage you to keep expressing your concerns, however I don't feel like we agree on this particular problem

Regards.

**Comment by thibaultmol** [comment] 2019-12-11 21:45
No that's fine yeah

I removed the previous cloud run instance just in case and deployed the new version. 
When I try to parse a file trough it I get this error: https://drive.google.com/open?id=12d0-dTKT2mDPmBuX2VnSHxi5l4cqpzyX 

Some other feature requests:
- dropdown menu for the available languages on the front end.
- Also, I'd like to add recognisitionmetadata: https://cloud.google.com/speech-to-text/docs/recognition-metadata.

**Comment by LuisMayo** [comment] 2019-12-11 22:58
@thibaultmol 
I've opened several issues to address the enhancements you proposed

About the error you gave me I think I have done a poor job explaining how to use this (tbf, this was a personal project I didn't even expect anybody to get interested about it)

I'll explain the workflow in this message

(Once everything is set up)
1. The user goes to the frontend. The user is required to fill some fields, including

1. Backend URL(this may be already filled): URL to find the backend server
2. Media URL: URL to find a media file
3. Name, nothing relevant

2. Once the user fills these fields then the frontend application makes a request to de Google Run Powered backend application
3. The backend recieves the petition and starts processing it, including:
1. It will **Download** the media file from the URL the user set
2. It will extract the audio from the file into a FLAC file
3. It will upload the FLAC into the GCS bucket specified during install
4. It will ask GC's STT API to process the audio
5. It will Download the json response.
6. It will convert the response into a SRT file using my own Google STT to SRT library
7. It will give the SRT back to the frontend

Then the frontend will show the SRT to the user allowing him to download it

So what does all of this means?
Well if you read carefully you will notice that the backend DOES NOT accept an audio file, nor a filename, it accepts an URL, which means than the Audio file must be publicly available on the internet so the backend can download this file from the internet prior to processing it

Solution to your problem? Upload the filename somewhere in the internet where you can get a direct link.
For example, this would be a good link, if you use this link the all should work:
http://www.voiptroubleshooter.com/open_speech/american/OSR_us_000_0010_8k.wav
[Source](http://www.voiptroubleshooter.com/open_speech/american.html)

Do you want to be able to directly upload the file instead of providing an URL?
I admit that it would be handy and I'll make an issue to address it but currently you need to provide an URL of a file on the internet

Regards

**Comment by LuisMayo** [comment] 2019-12-12 20:55
Hi again @thibaultmol 
Just FYI. Now you're able to select a file of your computer and send it to the server without specifying an URL.

You'll need to update your Google Cloud Run Service for this to work

Regards.

**Comment by thibaultmol** [comment] 2019-12-14 21:48
nice thx! 
You still need to upload the file from the front end, trough the cloud run instance, to the storage bucket, right?
I wonder if what I'm doing wrong has something do with the bucket not having permissions. But I haven't used GCP much so I don't know exactly what steps I need to do for that.
Also, maybe the intitial setup could setup it's own bucket, so it would get the permission for it anyway if that's needed.

This is the latest log from stackdriver: https://drive.google.com/open?id=12reDjfDy2aS9YdvlsFVy6NvM4Bk4UAOk

This is the file I'm trying to processs btw: https://drive.google.com/open?id=12t3kFVPK8wDA5MN-RHMmbPEaUhEWwWZ9 (language is nl-NL)

**Comment by LuisMayo** [comment] 2019-12-15 00:08
@thibaultmol I think in fact the standard user need to have permissions to the bucket
My setup is pretty complicated since in the past I used a in system consisting in 4 cloud functions so a lot of permissions are involved

I'll make a new project later to check which permissions do you need to work

Your file is not working for me either, I'll check later why

Regards

**Comment by LuisMayo** [comment] 2019-12-15 01:11
@thibaultmol I think this may be the problem to your file:
https://cloud.google.com/run/quotas
As stated there, the maximum http request size is 32MB which may be even lower as audio has to be encoded into base64 in order for it to be sent

This may be circumvented by setting an app engine/compute engine instance instead of a Cloud run but this is slightly out of scope. You should upload the file anywhere that gives you a direct link(i.e a link in which the media file that could be downloaded using right button --> save as..., If you click it directly chrome's default media player will reproduce it). I think MediaFire used to allow you do that but IDK if it'll still allow you
If not uploading it to any web hosting would get you a direct link, even a Github page would do the trick, check https://free-for.dev/#/?id=web-hosting to see what could fit you
Regards

I'll put a size limit on the front so this confusion is no longer made

Sorry the project is being that hard for you. At this point it'll be easier to just upload a blank video to YouTube and let it generate the srt... XD

Regards.
